language: r
cache: packages
warnings_are_errors: true
r_packages:
  - pkgdown

after_success:
  - Rscript -e 'covr::codecov()'
  - bash <(curl -s https://codecov.io/bash)
  
addons:
  apt:
    sources:
      - sourceline: 'ppa:chris-lea/libsodium'
    packages:
      - libsodium-dev
      - libicu-dev

deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github(verbose = TRUE)'
  skip_cleanup: true

stages:
  - name: deploy
    if: branch = master
